import ItemModal from "@/components/ItemModal";
import type { ShoppingItem } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

import { trpc } from "../utils/trpc";

// const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
const Home: NextPage = () => {
  const [modalOpen, setModalOpen] = useState(false);
  const [items, setItems] = useState<ShoppingItem[]>([]);

  const { data: shoppingItems, isLoading } = trpc.item.getAll.useQuery(
    undefined,
    { onSuccess: (data) => setItems(data) }
  );

  if (!shoppingItems || isLoading) return <div>Loading....</div>;

  const handleToggleItemModal = () => setModalOpen((prevState) => !prevState);

  return (
    <>
      <Head>
        <title>Shopping list</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto my-12 max-w-3xl px-6">
        <div className="flex justify-between">
          <h2 className="text-2xl font-semibold">My shopping list</h2>
          <button
            type="button"
            onClick={handleToggleItemModal}
            className="rounded-md bg-violet-500 p-2 text-sm text-white transition hover:bg-violet-600"
          >
            Add shopping item
          </button>
        </div>
        <ul className="mt-8 space-y-4">
          {items.map((item) => {
            return (
              <li key={item.id}>
                <div className="flex items-center justify-between">
                  {item.name}
                </div>
              </li>
            );
          })}
        </ul>
      </main>

      {modalOpen && (
        <ItemModal onToggle={handleToggleItemModal} setItems={setItems} />
      )}
    </>
  );
};

export default Home;
