import type { ShoppingItem } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [items, setItems] = useState<ShoppingItem[]>([]);
  const { mutate: addItem } = trpc.item.addItem.useMutation({
    onSuccess: (shoppingItem) => {
      setItems([...items, shoppingItem]);
    },
  });
  // const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  const handlerAddItenToCart = () => addItem({ name: "firstItemAdded" });

  console.log("renders  🚀", { items, addItem });

  return (
    <>
      <Head>
        <title>Shopping list</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex justify-between">
          <h2 className="text-2xl font-semibold">My shopping list</h2>
          <button
            type="button"
            onClick={handlerAddItenToCart}
            className="rounded-md bg-violet-500 p-2 text-sm text-white transition hover:bg-violet-600"
          >
            Add shopping item
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
